/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedLeoRouteImport } from './routes/_authenticated/leo'
import { Route as AuthenticatedLionRouteImport } from './routes/_authenticated/lion'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedLeoIndexRouteImport } from './routes/_authenticated/leo.index'
import { Route as AuthenticatedLeoAnalyticsRouteImport } from './routes/_authenticated/leo.analytics'
import { Route as AuthenticatedLeoCalendrierRouteImport } from './routes/_authenticated/leo.calendrier'
import { Route as AuthenticatedLeoClassementRouteImport } from './routes/_authenticated/leo.classement'
import { Route as AuthenticatedLeoFichiersRouteImport } from './routes/_authenticated/leo.fichiers'
import { Route as AuthenticatedLeoNotesRouteImport } from './routes/_authenticated/leo.notes'
import { Route as AuthenticatedLeoPinsRouteImport } from './routes/_authenticated/leo.pins'
import { Route as AuthenticatedLeoVentesRouteImport } from './routes/_authenticated/leo.ventes'
import { Route as AuthenticatedLionIndexRouteImport } from './routes/_authenticated/lion.index'
import { Route as AuthenticatedLionCalendrierRouteImport } from './routes/_authenticated/lion.calendrier'
import { Route as AuthenticatedLionNotesRouteImport } from './routes/_authenticated/lion.notes'
import { Route as AuthenticatedLionRestaurantsRouteImport } from './routes/_authenticated/lion.restaurants'
import { Route as ApiPublicPinterestCallbackRouteImport } from './routes/api/public/pinterest/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeoRoute = AuthenticatedLeoRouteImport.update({
  id: '/leo',
  path: '/leo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLionRoute = AuthenticatedLionRouteImport.update({
  id: '/lion',
  path: '/lion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeoIndexRoute = AuthenticatedLeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLeoAnalyticsRoute =
  AuthenticatedLeoAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedLeoRoute,
  } as any)
const AuthenticatedLeoCalendrierRoute =
  AuthenticatedLeoCalendrierRouteImport.update({
    id: '/calendrier',
    path: '/calendrier',
    getParentRoute: () => AuthenticatedLeoRoute,
  } as any)
const AuthenticatedLeoClassementRoute =
  AuthenticatedLeoClassementRouteImport.update({
    id: '/classement',
    path: '/classement',
    getParentRoute: () => AuthenticatedLeoRoute,
  } as any)
const AuthenticatedLeoFichiersRoute =
  AuthenticatedLeoFichiersRouteImport.update({
    id: '/fichiers',
    path: '/fichiers',
    getParentRoute: () => AuthenticatedLeoRoute,
  } as any)
const AuthenticatedLeoNotesRoute = AuthenticatedLeoNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLeoPinsRoute = AuthenticatedLeoPinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLeoVentesRoute = AuthenticatedLeoVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLionIndexRoute = AuthenticatedLionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLionRoute,
} as any)
const AuthenticatedLionCalendrierRoute =
  AuthenticatedLionCalendrierRouteImport.update({
    id: '/calendrier',
    path: '/calendrier',
    getParentRoute: () => AuthenticatedLionRoute,
  } as any)
const AuthenticatedLionNotesRoute = AuthenticatedLionNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedLionRoute,
} as any)
const AuthenticatedLionRestaurantsRoute =
  AuthenticatedLionRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => AuthenticatedLionRoute,
  } as any)
const ApiPublicPinterestCallbackRoute =
  ApiPublicPinterestCallbackRouteImport.update({
    id: '/api/public/pinterest/callback',
    path: '/api/public/pinterest/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/hub': typeof AuthenticatedHubRoute
  '/leo': typeof AuthenticatedLeoRouteWithChildren
  '/lion': typeof AuthenticatedLionRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/leo/analytics': typeof AuthenticatedLeoAnalyticsRoute
  '/leo/calendrier': typeof AuthenticatedLeoCalendrierRoute
  '/leo/classement': typeof AuthenticatedLeoClassementRoute
  '/leo/fichiers': typeof AuthenticatedLeoFichiersRoute
  '/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/leo/ventes': typeof AuthenticatedLeoVentesRoute
  '/lion/calendrier': typeof AuthenticatedLionCalendrierRoute
  '/lion/notes': typeof AuthenticatedLionNotesRoute
  '/lion/restaurants': typeof AuthenticatedLionRestaurantsRoute
  '/leo/': typeof AuthenticatedLeoIndexRoute
  '/lion/': typeof AuthenticatedLionIndexRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/hub': typeof AuthenticatedHubRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/leo/analytics': typeof AuthenticatedLeoAnalyticsRoute
  '/leo/calendrier': typeof AuthenticatedLeoCalendrierRoute
  '/leo/classement': typeof AuthenticatedLeoClassementRoute
  '/leo/fichiers': typeof AuthenticatedLeoFichiersRoute
  '/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/leo/ventes': typeof AuthenticatedLeoVentesRoute
  '/lion/calendrier': typeof AuthenticatedLionCalendrierRoute
  '/lion/notes': typeof AuthenticatedLionNotesRoute
  '/lion/restaurants': typeof AuthenticatedLionRestaurantsRoute
  '/leo': typeof AuthenticatedLeoIndexRoute
  '/lion': typeof AuthenticatedLionIndexRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/leo': typeof AuthenticatedLeoRouteWithChildren
  '/_authenticated/lion': typeof AuthenticatedLionRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/leo/analytics': typeof AuthenticatedLeoAnalyticsRoute
  '/_authenticated/leo/calendrier': typeof AuthenticatedLeoCalendrierRoute
  '/_authenticated/leo/classement': typeof AuthenticatedLeoClassementRoute
  '/_authenticated/leo/fichiers': typeof AuthenticatedLeoFichiersRoute
  '/_authenticated/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/_authenticated/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/_authenticated/leo/ventes': typeof AuthenticatedLeoVentesRoute
  '/_authenticated/lion/calendrier': typeof AuthenticatedLionCalendrierRoute
  '/_authenticated/lion/notes': typeof AuthenticatedLionNotesRoute
  '/_authenticated/lion/restaurants': typeof AuthenticatedLionRestaurantsRoute
  '/_authenticated/leo/': typeof AuthenticatedLeoIndexRoute
  '/_authenticated/lion/': typeof AuthenticatedLionIndexRoute
  '/api/public/pinterest/callback': typeof ApiPublicPinterestCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/calendrier'
    | '/hub'
    | '/leo'
    | '/lion'
    | '/notes'
    | '/leo/analytics'
    | '/leo/calendrier'
    | '/leo/classement'
    | '/leo/fichiers'
    | '/leo/notes'
    | '/leo/pins'
    | '/leo/ventes'
    | '/lion/calendrier'
    | '/lion/notes'
    | '/lion/restaurants'
    | '/leo/'
    | '/lion/'
    | '/api/public/pinterest/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/calendrier'
    | '/hub'
    | '/notes'
    | '/leo/analytics'
    | '/leo/calendrier'
    | '/leo/classement'
    | '/leo/fichiers'
    | '/leo/notes'
    | '/leo/pins'
    | '/leo/ventes'
    | '/lion/calendrier'
    | '/lion/notes'
    | '/lion/restaurants'
    | '/leo'
    | '/lion'
    | '/api/public/pinterest/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/calendrier'
    | '/_authenticated/hub'
    | '/_authenticated/leo'
    | '/_authenticated/lion'
    | '/_authenticated/notes'
    | '/_authenticated/leo/analytics'
    | '/_authenticated/leo/calendrier'
    | '/_authenticated/leo/classement'
    | '/_authenticated/leo/fichiers'
    | '/_authenticated/leo/notes'
    | '/_authenticated/leo/pins'
    | '/_authenticated/leo/ventes'
    | '/_authenticated/lion/calendrier'
    | '/_authenticated/lion/notes'
    | '/_authenticated/lion/restaurants'
    | '/_authenticated/leo/'
    | '/_authenticated/lion/'
    | '/api/public/pinterest/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPinterestCallbackRoute: typeof ApiPublicPinterestCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leo': {
      id: '/_authenticated/leo'
      path: '/leo'
      fullPath: '/leo'
      preLoaderRoute: typeof AuthenticatedLeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lion': {
      id: '/_authenticated/lion'
      path: '/lion'
      fullPath: '/lion'
      preLoaderRoute: typeof AuthenticatedLionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leo/': {
      id: '/_authenticated/leo/'
      path: '/'
      fullPath: '/leo/'
      preLoaderRoute: typeof AuthenticatedLeoIndexRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/analytics': {
      id: '/_authenticated/leo/analytics'
      path: '/analytics'
      fullPath: '/leo/analytics'
      preLoaderRoute: typeof AuthenticatedLeoAnalyticsRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/calendrier': {
      id: '/_authenticated/leo/calendrier'
      path: '/calendrier'
      fullPath: '/leo/calendrier'
      preLoaderRoute: typeof AuthenticatedLeoCalendrierRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/classement': {
      id: '/_authenticated/leo/classement'
      path: '/classement'
      fullPath: '/leo/classement'
      preLoaderRoute: typeof AuthenticatedLeoClassementRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/fichiers': {
      id: '/_authenticated/leo/fichiers'
      path: '/fichiers'
      fullPath: '/leo/fichiers'
      preLoaderRoute: typeof AuthenticatedLeoFichiersRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/notes': {
      id: '/_authenticated/leo/notes'
      path: '/notes'
      fullPath: '/leo/notes'
      preLoaderRoute: typeof AuthenticatedLeoNotesRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/pins': {
      id: '/_authenticated/leo/pins'
      path: '/pins'
      fullPath: '/leo/pins'
      preLoaderRoute: typeof AuthenticatedLeoPinsRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/ventes': {
      id: '/_authenticated/leo/ventes'
      path: '/ventes'
      fullPath: '/leo/ventes'
      preLoaderRoute: typeof AuthenticatedLeoVentesRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/lion/': {
      id: '/_authenticated/lion/'
      path: '/'
      fullPath: '/lion/'
      preLoaderRoute: typeof AuthenticatedLionIndexRouteImport
      parentRoute: typeof AuthenticatedLionRoute
    }
    '/_authenticated/lion/calendrier': {
      id: '/_authenticated/lion/calendrier'
      path: '/calendrier'
      fullPath: '/lion/calendrier'
      preLoaderRoute: typeof AuthenticatedLionCalendrierRouteImport
      parentRoute: typeof AuthenticatedLionRoute
    }
    '/_authenticated/lion/notes': {
      id: '/_authenticated/lion/notes'
      path: '/notes'
      fullPath: '/lion/notes'
      preLoaderRoute: typeof AuthenticatedLionNotesRouteImport
      parentRoute: typeof AuthenticatedLionRoute
    }
    '/_authenticated/lion/restaurants': {
      id: '/_authenticated/lion/restaurants'
      path: '/restaurants'
      fullPath: '/lion/restaurants'
      preLoaderRoute: typeof AuthenticatedLionRestaurantsRouteImport
      parentRoute: typeof AuthenticatedLionRoute
    }
    '/api/public/pinterest/callback': {
      id: '/api/public/pinterest/callback'
      path: '/api/public/pinterest/callback'
      fullPath: '/api/public/pinterest/callback'
      preLoaderRoute: typeof ApiPublicPinterestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLeoRouteChildren {
  AuthenticatedLeoAnalyticsRoute: typeof AuthenticatedLeoAnalyticsRoute
  AuthenticatedLeoCalendrierRoute: typeof AuthenticatedLeoCalendrierRoute
  AuthenticatedLeoClassementRoute: typeof AuthenticatedLeoClassementRoute
  AuthenticatedLeoFichiersRoute: typeof AuthenticatedLeoFichiersRoute
  AuthenticatedLeoNotesRoute: typeof AuthenticatedLeoNotesRoute
  AuthenticatedLeoPinsRoute: typeof AuthenticatedLeoPinsRoute
  AuthenticatedLeoVentesRoute: typeof AuthenticatedLeoVentesRoute
  AuthenticatedLeoIndexRoute: typeof AuthenticatedLeoIndexRoute
}

const AuthenticatedLeoRouteChildren: AuthenticatedLeoRouteChildren = {
  AuthenticatedLeoAnalyticsRoute: AuthenticatedLeoAnalyticsRoute,
  AuthenticatedLeoCalendrierRoute: AuthenticatedLeoCalendrierRoute,
  AuthenticatedLeoClassementRoute: AuthenticatedLeoClassementRoute,
  AuthenticatedLeoFichiersRoute: AuthenticatedLeoFichiersRoute,
  AuthenticatedLeoNotesRoute: AuthenticatedLeoNotesRoute,
  AuthenticatedLeoPinsRoute: AuthenticatedLeoPinsRoute,
  AuthenticatedLeoVentesRoute: AuthenticatedLeoVentesRoute,
  AuthenticatedLeoIndexRoute: AuthenticatedLeoIndexRoute,
}

const AuthenticatedLeoRouteWithChildren =
  AuthenticatedLeoRoute._addFileChildren(AuthenticatedLeoRouteChildren)

interface AuthenticatedLionRouteChildren {
  AuthenticatedLionCalendrierRoute: typeof AuthenticatedLionCalendrierRoute
  AuthenticatedLionNotesRoute: typeof AuthenticatedLionNotesRoute
  AuthenticatedLionRestaurantsRoute: typeof AuthenticatedLionRestaurantsRoute
  AuthenticatedLionIndexRoute: typeof AuthenticatedLionIndexRoute
}

const AuthenticatedLionRouteChildren: AuthenticatedLionRouteChildren = {
  AuthenticatedLionCalendrierRoute: AuthenticatedLionCalendrierRoute,
  AuthenticatedLionNotesRoute: AuthenticatedLionNotesRoute,
  AuthenticatedLionRestaurantsRoute: AuthenticatedLionRestaurantsRoute,
  AuthenticatedLionIndexRoute: AuthenticatedLionIndexRoute,
}

const AuthenticatedLionRouteWithChildren =
  AuthenticatedLionRoute._addFileChildren(AuthenticatedLionRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedLeoRoute: typeof AuthenticatedLeoRouteWithChildren
  AuthenticatedLionRoute: typeof AuthenticatedLionRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedLeoRoute: AuthenticatedLeoRouteWithChildren,
  AuthenticatedLionRoute: AuthenticatedLionRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPinterestCallbackRoute: ApiPublicPinterestCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
