/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedLeoRouteImport } from './routes/_authenticated/leo'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedLeoIndexRouteImport } from './routes/_authenticated/leo.index'
import { Route as AuthenticatedLeoNotesRouteImport } from './routes/_authenticated/leo.notes'
import { Route as AuthenticatedLeoPinsRouteImport } from './routes/_authenticated/leo.pins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeoRoute = AuthenticatedLeoRouteImport.update({
  id: '/leo',
  path: '/leo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeoIndexRoute = AuthenticatedLeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLeoNotesRoute = AuthenticatedLeoNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)
const AuthenticatedLeoPinsRoute = AuthenticatedLeoPinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => AuthenticatedLeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/hub': typeof AuthenticatedHubRoute
  '/leo': typeof AuthenticatedLeoRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/leo/': typeof AuthenticatedLeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/hub': typeof AuthenticatedHubRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/leo': typeof AuthenticatedLeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/leo': typeof AuthenticatedLeoRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/leo/notes': typeof AuthenticatedLeoNotesRoute
  '/_authenticated/leo/pins': typeof AuthenticatedLeoPinsRoute
  '/_authenticated/leo/': typeof AuthenticatedLeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendrier'
    | '/hub'
    | '/leo'
    | '/notes'
    | '/leo/notes'
    | '/leo/pins'
    | '/leo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendrier'
    | '/hub'
    | '/notes'
    | '/leo/notes'
    | '/leo/pins'
    | '/leo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendrier'
    | '/_authenticated/hub'
    | '/_authenticated/leo'
    | '/_authenticated/notes'
    | '/_authenticated/leo/notes'
    | '/_authenticated/leo/pins'
    | '/_authenticated/leo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leo': {
      id: '/_authenticated/leo'
      path: '/leo'
      fullPath: '/leo'
      preLoaderRoute: typeof AuthenticatedLeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leo/': {
      id: '/_authenticated/leo/'
      path: '/'
      fullPath: '/leo/'
      preLoaderRoute: typeof AuthenticatedLeoIndexRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/notes': {
      id: '/_authenticated/leo/notes'
      path: '/notes'
      fullPath: '/leo/notes'
      preLoaderRoute: typeof AuthenticatedLeoNotesRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
    '/_authenticated/leo/pins': {
      id: '/_authenticated/leo/pins'
      path: '/pins'
      fullPath: '/leo/pins'
      preLoaderRoute: typeof AuthenticatedLeoPinsRouteImport
      parentRoute: typeof AuthenticatedLeoRoute
    }
  }
}

interface AuthenticatedLeoRouteChildren {
  AuthenticatedLeoNotesRoute: typeof AuthenticatedLeoNotesRoute
  AuthenticatedLeoPinsRoute: typeof AuthenticatedLeoPinsRoute
  AuthenticatedLeoIndexRoute: typeof AuthenticatedLeoIndexRoute
}

const AuthenticatedLeoRouteChildren: AuthenticatedLeoRouteChildren = {
  AuthenticatedLeoNotesRoute: AuthenticatedLeoNotesRoute,
  AuthenticatedLeoPinsRoute: AuthenticatedLeoPinsRoute,
  AuthenticatedLeoIndexRoute: AuthenticatedLeoIndexRoute,
}

const AuthenticatedLeoRouteWithChildren =
  AuthenticatedLeoRoute._addFileChildren(AuthenticatedLeoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedLeoRoute: typeof AuthenticatedLeoRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedLeoRoute: AuthenticatedLeoRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
